[2025-05-04 15:23:38,328: INFO: main: Welcome to our Custome Log]
[2025-05-04 19:31:01,164: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-04 19:31:01,192: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-04 19:31:01,194: INFO: common: created directory at: artifacts]
[2025-05-04 19:31:01,204: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-04 19:31:01,208: INFO: 1579108944: Downloading data from https://drive.google.com/file/d/1shj8hWecNdvztImitfcVKKdbQmZbTcFz/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-05-04 19:34:23,688: INFO: 1579108944: Downloaded data from https://drive.google.com/file/d/1shj8hWecNdvztImitfcVKKdbQmZbTcFz/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-05-04 23:38:38,437: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-05-04 23:38:38,445: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-04 23:38:38,447: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-04 23:38:38,447: INFO: common: created directory at: artifacts]
[2025-05-04 23:38:38,447: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-04 23:38:38,447: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1shj8hWecNdvztImitfcVKKdbQmZbTcFz/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-05-04 23:41:41,491: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1shj8hWecNdvztImitfcVKKdbQmZbTcFz/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-05-04 23:42:07,967: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-05-05 14:02:17,420: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 14:02:17,541: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 14:02:17,553: INFO: common: created directory at: artifacts]
[2025-05-05 14:02:17,557: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-05 14:02:36,180: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-05 14:14:04,211: INFO: main: *******************]
[2025-05-05 14:14:04,211: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-05 14:14:04,212: ERROR: main: name 'PrepareBaseModelTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    prepare_base_model = PrepareBaseModelTrainingPipeline()
NameError: name 'PrepareBaseModelTrainingPipeline' is not defined
[2025-05-05 14:16:54,426: INFO: main: *******************]
[2025-05-05 14:16:54,426: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-05 14:16:54,437: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 14:16:54,457: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 14:16:54,459: INFO: common: created directory at: artifacts]
[2025-05-05 14:16:54,459: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-05 14:16:55,393: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-05 14:16:56,003: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-05 14:22:21,497: INFO: main: *******************]
[2025-05-05 14:22:21,497: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-05 14:22:21,497: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 14:22:21,506: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 14:22:21,509: INFO: common: created directory at: artifacts]
[2025-05-05 14:22:21,511: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-05 14:22:22,542: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-05 14:22:23,019: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-05 14:34:30,261: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 14:34:30,271: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 14:34:30,291: INFO: common: created directory at: artifacts]
[2025-05-05 14:34:30,295: INFO: common: created directory at: artifacts\training]
[2025-05-05 14:35:23,747: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 14:35:23,754: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 14:35:23,758: INFO: common: created directory at: artifacts]
[2025-05-05 14:35:23,760: INFO: common: created directory at: artifacts\training]
[2025-05-05 14:36:15,530: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 14:36:15,554: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 14:36:15,562: INFO: common: created directory at: artifacts]
[2025-05-05 14:36:15,567: INFO: common: created directory at: artifacts\training]
[2025-05-05 14:44:59,201: INFO: main: *******************]
[2025-05-05 14:44:59,203: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-05 14:44:59,210: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 14:44:59,210: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 14:44:59,210: INFO: common: created directory at: artifacts]
[2025-05-05 14:44:59,210: ERROR: main: name 'os' is not defined]
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    model_trainer.main()
  File "c:\users\ishant\documents\data_science_project\kidney_disease_classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training_config = config.get_training_config()
  File "c:\users\ishant\documents\data_science_project\kidney_disease_classification-mlflow-dvc\src\cnnClassifier\config\configuration.py", line 57, in get_training_config
    training_data = os.path.join(self.config.data_ingestion.unzip_dir, "kidney-ct-scan-image")
NameError: name 'os' is not defined
[2025-05-05 14:45:55,295: INFO: main: *******************]
[2025-05-05 14:45:55,295: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-05 14:45:55,310: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 14:45:55,310: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 14:45:55,310: INFO: common: created directory at: artifacts]
[2025-05-05 14:45:55,310: ERROR: main: name 'os' is not defined]
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    model_trainer.main()
  File "c:\users\ishant\documents\data_science_project\kidney_disease_classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training_config = config.get_training_config()
  File "c:\users\ishant\documents\data_science_project\kidney_disease_classification-mlflow-dvc\src\cnnClassifier\config\configuration.py", line 57, in get_training_config
    training_data = os.path.join(self.config.data_ingestion.unzip_dir, "Dataset")
NameError: name 'os' is not defined
[2025-05-05 14:49:27,277: INFO: main: *******************]
[2025-05-05 14:49:27,277: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-05 14:49:27,286: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 14:49:27,288: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 14:49:27,288: INFO: common: created directory at: artifacts]
[2025-05-05 14:49:27,288: ERROR: main: name 'os' is not defined]
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    model_trainer.main()
  File "c:\users\ishant\documents\data_science_project\kidney_disease_classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training_config = config.get_training_config()
  File "c:\users\ishant\documents\data_science_project\kidney_disease_classification-mlflow-dvc\src\cnnClassifier\config\configuration.py", line 57, in get_training_config
    training_data = os.path.join(self.config.data_ingestion.unzip_dir, "Dataset")
NameError: name 'os' is not defined
[2025-05-05 14:50:56,421: INFO: main: *******************]
[2025-05-05 14:50:56,421: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-05 14:50:56,421: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 14:50:56,421: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 14:50:56,421: INFO: common: created directory at: artifacts]
[2025-05-05 14:50:56,421: INFO: common: created directory at: artifacts\training]
[2025-05-05 15:41:03,092: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
